use rayon::prelude::*;

const EXAMPLE_ANSWER: usize = 4174379265;

aoc::solution!(EXAMPLE_ANSWER, solve);

fn solve(input: &str) -> usize {
    input
        .split(',')
        .par_bridge() // Parallelize per input range just in case
        .map(|range| {
            let mut parts = range.split('-');
            let start = parts.next().unwrap().trim().parse::<usize>().unwrap();
            let end = parts.next().unwrap().trim().parse::<usize>().unwrap();
            solve_range(start, end)
        })
        .sum()
}

fn solve_range(start: usize, end: usize) -> usize {
    let mut total_sum = 0;

    for d in 2..=19 {
        // Find all valid chunk counts 'k'. 
        // A number length D can be split into k chunks of length L.
        for k in 2..=d {
            if d % k == 0 {
                let l = d / k; // Length of the seed
                
                // Multiplier to turn seed X into repeated number N
                let multiplier = repetition_multiplier(l, k);
                
                // Define the range for the SEED X
                let min_x = (start + multiplier - 1) / multiplier;
                let max_x = end / multiplier;
                
                // Get sum of primitive seeds in this range
                let sum_primitive = get_primitive_seed_sum(l, min_x, max_x);
                
                // sum_primitive is u128, multiplier is usize
                let term = sum_primitive.wrapping_mul(multiplier as u128);
                total_sum += term as usize;
            }
        }
    }
    total_sum
}

// Recursively calculates the sum of seeds of length `len` that are PRIMITIVE.
// Primitive means the seed cannot be formed by repeating a smaller sub-seed.
fn get_primitive_seed_sum(len: u32, min_val: usize, max_val: usize) -> u128 {
    let base_min = 10usize.pow(len - 1);
    let base_max = 10usize.pow(len) - 1;

    let actual_min = min_val.max(base_min);
    let actual_max = max_val.min(base_max);

    if actual_min > actual_max {
        return 0;
    }

    // Arithmetic progression sum: Count * (A + B) / 2
    let count = (actual_max - actual_min + 1) as u128;
    let sum_all = count * (actual_min as u128 + actual_max as u128) / 2;

    let mut sum_non_primitive = 0;

    // 2. Subtract numbers generated by smaller seeds
    // Iterate divisors of 'len'. 
    // If len=4, we check sub_len=1 and sub_len=2.
    for k in 2..=len {
        if len % k == 0 {
            let sub_len = len / k;
            
            // Calculate how the smaller seed scales to the current length
            let sub_multiplier = repetition_multiplier(sub_len, k);

            // Bounds for the smaller seed
            let sub_min_req = (actual_min + sub_multiplier - 1) / sub_multiplier;
            let sub_max_req = actual_max / sub_multiplier;

            // RECURSE: Get sum of primitive seeds for the smaller length
            let prim_sub_sum = get_primitive_seed_sum(sub_len, sub_min_req, sub_max_req);
            
            sum_non_primitive += prim_sub_sum * sub_multiplier as u128;
        }
    }

    sum_all - sum_non_primitive
}

fn repetition_multiplier(len: u32, k: u32) -> usize {
    // geometric series: sum(10^(i*len)) for i in 0..k
    // simpler: (10^(len*k) - 1) / (10^len - 1)
    
    let num = 10u128.pow(len * k) - 1;
    let den = 10u128.pow(len) - 1;
    (num / den) as usize
}
