[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[lib]
name = "aoc"
path = "aoc.rs"

[[bin]]
name = "1_1"
path = "./01/part1.rs"

[[bin]]
name = "1_2"
path = "./01/part2.rs"

[[bin]]
name = "2_1"
path = "./02/part1.rs"

[[bin]]
name = "2_2"
path = "./02/part2.rs"

[[bin]]
name = "3_1"
path = "./03/part1.rs"

[[bin]]
name = "3_2"
path = "./03/part2.rs"

[[bin]]
name = "4_1"
path = "./04/part1.rs"

[[bin]]
name = "4_2"
path = "./04/part2.rs"

[[bin]]
name = "5_1"
path = "./05/part1.rs"

[[bin]]
name = "5_2"
path = "./05/part2.rs"

[[bin]]
name = "6_1"
path = "./06/part1.rs"

[[bin]]
name = "6_2"
path = "./06/part2.rs"

[[bin]]
name = "7_1"
path = "./07/part1.rs"

[[bin]]
name = "7_2"
path = "./07/part2.rs"

[[bin]]
name = "8_1"
path = "./08/part1.rs"

[[bin]]
name = "8_2"
path = "./08/part2.rs"

[dependencies]
itertools = "0.14.0"
memory-stats = "1.2.0"
rayon = "1.11.0"
